<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="growlt105" failures="1" tests="1" name="Test" time="14.076" errors="0" timestamp="2022-09-23T17:38:37 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="13.841">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 2 out of bounds for length 2">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:359)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at steps.loginStep.user_login_into_application_with_username_and_password(loginStep.java:30)
at âœ½.User login into application with username and password(file:///home/growlt105/eclipse-workspace/NavigatorAutomation/src/test/resources/Featuresfile/Login.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Test -->
